# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

    # Provision software
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
  end

  # Boot with a gui
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.gui = true
  end

  # Reboot for changes to take effect
  config.vm.provision "shell", inline: <<-SHELL
     shutdown -r now 
  SHELL
end
